### PR TITLE
Allow using custom ARM-based Docker images

### PR DESCRIPTION
**Pull request by orkhanahmadov**
This PR allows using custom ARM-based Docker images.

We always pre-build vapor image with extras (like Imagick extension), push it to AWS ECR then use that ECR image for deployments in `production.Dockerfile`. Disallowing custom ARM images prevents doing this.

### CODE REVIEW

**Comment by nunomaduro** [comment]
> Bugfix release [1.55.2](https://github.com/laravel/vapor-cli/releases/tag/v1.55.2) introduced a breaking change for everyone that uses custom Docker ARM images for deployments.

What do you mean by "introduced a breaking change", if we shipped ARM for docker yesterday? We still allow custom images if customers wish to build their own `amd64` image. However, for `arm64`, that we shipped yesterday, we are developing internally some things that we wish to ship before we allow our customers to build custom ARM builds.

**Comment by orkhanahmadov** [comment]
@nunomaduro sorry the for confusion. When we started having issues on our deployments and when started investigating the issue, also looking into new ARM-based images, the latest available versions of the package were `1.55.1` and `1.55.2` they both disallowed using **any** custom images, which was a breaking change. Now I noticed `1.55.3` was released and it also allows x86 Docker images again.

But I think you can still consider this PR since it also allows using ARM-based custom Docker images too.

**Comment by orkhanahmadov** [comment]
Just updated the PR title and description to better reflect the purpose of this PR.

**Comment by aubreychiduku** [comment]
I am attempting to deploy the `laravelphp/vapor:php82-arm` image and I'm seeing this error

> Status: Downloaded newer image for laravelphp/vapor:php82-arm                
>   Executing 2 build triggers                                                 
> Warning: Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested                                                                     
> Running in fbe581139d78                                                
>   Removing intermediate container fbe581139d78                                 
> Warning: Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested                                                                     
> Running in 065d770710ec                                                
>   exec /bin/sh: exec format error                                          
>                                                                             
>                                                                                
>   Error Output:                                                                
>   The command '/bin/sh -c if [ -z "$__VAPOR_RUNTIME" ] ; then     echo "No runtime provided. Please upgrade to the latest version of laravel/vapor-cli."  
>    ;     exit 1 ;     elif [ "$__VAPOR_RUNTIME" != "docker-arm" ] ; then       
>   echo "The provided runtime [$__VAPOR_RUNTIME] is not supported by the vapor:php82-arm base image." ;     exit 1 ;     fi' returned a non-zero code: 1 

My vapor runtime config:


> environments:
>     production:
>         runtime: docker-arm

  
  Is this relevant or should I open a support ticket?

**Comment by joedixon** [comment]
> Is this relevant or should I open a support ticket?

Hey @aubreychiduku can you open a support ticket for this please as it's an unrelated issue.

**Comment by orkhanahmadov** [comment]
More context:

To build the base image for ARM I also noticed that the image requires a `__VAPOR_RUNTIME` argument. We pass it manually:

```bash
docker build -t vapor-base . --build-arg __VAPOR_RUNTIME=docker-arm
```

I mentioned this to [Taylor's tweet](https://twitter.com/orkhanahmadov/status/1647993159014555648) with the ARM support announcement.

**Comment by joedixon** [comment]
Hey @orkhanahmadov we do plan to add support for custom images using the `docker-arm` runtime. However, we want to put some safeguards in place to prevent the accidental deployment of an Arm image to a Lambda running x86.

We would advise against pre-building your image until we have this update in place which should be in the coming days.

Closing this PR for now.

**Comment by pyr0hu** [comment]
@joedixon any updates on this one?

**Comment by imrodrigoalves** [comment]
@joedixon When should we expect this feature to be available?

**Comment by joedixon** [comment]
I'm going to give this another test, but assuming it all works as expected, I think we can get this merged now.

**Pull request merged**
