### PR TITLE
Increase Application Limit to 100MB

### PR DESCRIPTION
**Pull request by Rigby90**
This PR has mainly been opened as a 'talking point' and to understand the size limitations for Laravel Apps & their Vendor files on Vapor. As an application I'm developing has more than 45 MB of assets outside of the Vendor and Public directories.

The additional feature you've just announced of separating the vendor directory out both in terms of space and faster deployments is appreciated and a nice addition! For my use case I could split my code base into packages and therefore separating them out into the vendors folder.

However, when uploading direct to Lambda, the limit is 50MB, when uploading to Lambda via S3, which from what I can tell Vapor is doing, the limit is 250 MB according to articles that have tested limits on Lambda. 

The Serverless CLI is able to achieve sizes up to 250MB when using S3 as the source.

[https://dashbird.io/blog/exploring-lambda-limitations/](https://dashbird.io/blog/exploring-lambda-limitations/)

[https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3](https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3)

Removing this limit within my local copy of Vapor CLI allows me to upload a file that's double the current limit and appears to function perfectly fine? This allows me to get around the limit and get my app working.

[https://www.dropbox.com/s/nco1adnqemx265v/100mb.PNG?dl=0](https://www.dropbox.com/s/nco1adnqemx265v/100mb.PNG?dl=0)

[https://resilient-pond-csvcammlc6kk.vapor-farm-a1.com/](https://resilient-pond-csvcammlc6kk.vapor-farm-a1.com/)

However there still appears to be something in the way of allowing larger files. It uploads successfully to S3, but during the 'Updating Function Configurations' stage it fails, looking at the Lambda configuration, there's no env variables etc set, it just appears to be a blank Lambda setup.

[https://www.dropbox.com/s/8y9yt8g0b0y6azw/150mb-error.PNG?dl=0](https://www.dropbox.com/s/8y9yt8g0b0y6azw/150mb-error.PNG?dl=0)

Apologies if it's fired any alerts off your way!

### CODE REVIEW

**Comment by taylorotwell** [comment]
It's because when you unzip your exceeding the total unzipped allowed size (250mb). That is why your Update Function Configuration is breaking.

**Comment by Rigby90** [comment]
> It's because when you unzip your exceeding the total unzipped allowed size (250mb). That is why your Update Function Configuration is breaking.

Appreciate you taking your time to look into this and respond.

I've just downloaded 3 'app.zip' files from my S3 bucket, the one which is successful and the two which failed.

Successful ZIP -

Compressed: 106 MB
Uncompressed: 138 MB

First Failed ZIP (Seen in the screenshot) -

Compressed: 156 MB
Uncompressed: 180 MB

Second Failed ZIP -

Compressed: 206 MB
Uncompressed: 238 MB


Both failed ZIPs are below the 250 MB limit after being extracted.

However, on another note. When attempting to modify the Lambda configuration manually and pointing it to the ZIP file on S3, I recieve the following error "Unzipped size must be smaller than 140063207 bytes". Which would indicate the limit is 140 MB?

After a bit more reading, it looks as though I skimmed over a crucial bit of information -

"50 MB (zipped, for direct upload)
250 MB (unzipped, **including layers**)
3 MB (console editor)"

This would indicate the Vapor Runtime is using 110MB of the 250MB allocation, leaving 140 MB for the app.

In which case, would my initial increase of the limit from 50MB to 100MB be viable? But at the same time would it be worth changing the calculation from the 'compressed' size, to the 'uncompressed'? As it is the uncompressed value which matters and based on my testing above it can equate to a significant amount. I'm happy to submit a PR to change over the logic.

**Comment by taylorotwell** [comment]
Correct, you have to factor in the layers. We can't up the compressed size to 100mb. Too many applications would fail on extraction.

**Comment by Rigby90** [comment]
> Correct, you have to factor in the layers. We can't up the compressed size to 100mb. Too many applications would fail on extraction.

Sorry, I think I explained it wrong.

I meant, if we adjusted how we calculated the app size, rather than taking the size of the final ZIP (which is how it's done now `$size = round(filesize($this->buildPath.'/app.zip') / 1048576, 1);`) we calculate the total file sizes prior to compressing, after composer runs and the public assets are extracted. If it's less than 100 MB, we then proceed to ZIP up the contents and then continue along the process, this ensures that we get a true representation of it's size when it is extracted within Lambda and matches the Lambda restrictions but also gives us more wiggle room, as shown in the screenshots and comparisons above allowing you to change the logic so that `total uncompressed size < 100` or to really push it 130-140.


Ultimately, with regards to my issue, I'm happy to continue running a modified version which has an upped limit (now that I know it's, at max, 140MB with Vapor's layers). And I believe most of the users which have encountered the 45MB should now be resolved with the vendor separation yourself and themsaid have worked on.

Once again, appreciate your time reading through this issue and replying.

**Pull request closed without merging**
