### PR TITLE
Add option to exclude node_modules folder from deploy

### PR DESCRIPTION
**Pull request by d8vjork**
Hi there,

So this is my proposal as we're struggling integrating many stuff that was and still required on our CI (Gitlab), and there is where we're doing the deployments using Vapor CLI.

This will solve a problem we've caching the node_modules folder on our CI (from another job that does more things like authenticate to private NPM repositories, etc).

### TL;DR

Don't remove the _node_modules_ folder before entering the Vapor's build hook, instead, ignore it after or let users decide on it (e.g. using the ignore on their _vapor.yml_ files as it excludes just before the deploy process).

I know this is a possible break change but if there's another possible solution we'll be very grateful.

### CODE REVIEW

**Comment by taylorotwell** [comment]
We would probably need to make this opt-in - not remove it for everyone.

**Comment by d8vjork** [comment]
Ok, we talked on my company about making it an option defaulted to true and configurable on the vapor.yml file or as an option on the deploy command.

@taylorotwell what's your suggestion? We can open another PR with that so we don't mess sending this one

**Comment by d8vjork** [comment]
Ok, added the option to the Manifest, defaulted to true

**Comment by fgilio** [comment]
We were overriding `ApplicationFiles` to achieve this, thanks @d8vjork !

**Pull request merged**
